//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.03 at 05:42:31 ÏÂÎç CST 
//


package aa;

import javax.xml.bind.annotation.XmlRegistry;
import aa.SMSMessage.MessageBody;
import aa.SMSMessage.MessageBody.RAIDStatusDetail;
import aa.SMSMessage.MessageBody.RAIDStatusDetail.HDDStatus;
import aa.SMSMessage.MessageHeader;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the aa package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: aa
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MessageBody }
     * 
     */
    public MessageBody createSMSMessageMessageBody() {
        return new MessageBody();
    }

    /**
     * Create an instance of {@link SMSMessage }
     * 
     */
    public SMSMessage createSMSMessage() {
        return new SMSMessage();
    }

    /**
     * Create an instance of {@link HDDStatus }
     * 
     */
    public HDDStatus createSMSMessageMessageBodyRAIDStatusDetailHDDStatus() {
        return new HDDStatus();
    }

    /**
     * Create an instance of {@link MessageHeader }
     * 
     */
    public MessageHeader createSMSMessageMessageHeader() {
        return new MessageHeader();
    }

    /**
     * Create an instance of {@link RAIDStatusDetail }
     * 
     */
    public RAIDStatusDetail createSMSMessageMessageBodyRAIDStatusDetail() {
        return new RAIDStatusDetail();
    }

}
