//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.03 at 05:42:31 обнГ CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.sony.net/d-cinema/sms/2007b")
package aa;
