//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.03 at 05:42:31 ÏÂÎç CST 
//


package aa;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import aa.SMSMessage.MessageBody;
import aa.SMSMessage.MessageBody.RAIDStatusDetail;
import aa.SMSMessage.MessageBody.RAIDStatusDetail.HDDStatus;
import aa.SMSMessage.MessageHeader;


/**
 * <p>Java class for SMSMessage element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="SMSMessage">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="MessageHeader">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                     &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                     &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="MessageBody">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="RAIDStatusDetail">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="RAIDStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="HDDStatus" maxOccurs="unbounded" minOccurs="0">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                         &lt;element name="IsSpareSlot" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageHeader",
    "messageBody"
})
@XmlRootElement(name = "SMSMessage")
public class SMSMessage {

    @XmlElement(name = "MessageHeader", namespace = "http://xmlns.sony.net/d-cinema/sms/2007b", required = true)
    protected MessageHeader messageHeader;
    @XmlElement(name = "MessageBody", namespace = "http://xmlns.sony.net/d-cinema/sms/2007b", required = true)
    protected MessageBody messageBody;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeader }
     *     
     */
    public MessageHeader getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeader }
     *     
     */
    public void setMessageHeader(MessageHeader value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the messageBody property.
     * 
     * @return
     *     possible object is
     *     {@link MessageBody }
     *     
     */
    public MessageBody getMessageBody() {
        return messageBody;
    }

    /**
     * Sets the value of the messageBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageBody }
     *     
     */
    public void setMessageBody(MessageBody value) {
        this.messageBody = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RAIDStatusDetail">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RAIDStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="HDDStatus" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="IsSpareSlot" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "raidStatusDetail"
    })
    public static class MessageBody {

        @XmlElement(name = "RAIDStatusDetail", namespace = "http://xmlns.sony.net/d-cinema/sms/2007b", required = true)
        protected RAIDStatusDetail raidStatusDetail;

        /**
         * Gets the value of the raidStatusDetail property.
         * 
         * @return
         *     possible object is
         *     {@link RAIDStatusDetail }
         *     
         */
        public RAIDStatusDetail getRAIDStatusDetail() {
            return raidStatusDetail;
        }

        /**
         * Sets the value of the raidStatusDetail property.
         * 
         * @param value
         *     allowed object is
         *     {@link RAIDStatusDetail }
         *     
         */
        public void setRAIDStatusDetail(RAIDStatusDetail value) {
            this.raidStatusDetail = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RAIDStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="HDDStatus" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="IsSpareSlot" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "raidStatus",
            "hddStatus"
        })
        public static class RAIDStatusDetail {

            @XmlElement(name = "RAIDStatus", namespace = "http://xmlns.sony.net/d-cinema/sms/2007b", required = true)
            protected String raidStatus;
            @XmlElement(name = "HDDStatus", namespace = "http://xmlns.sony.net/d-cinema/sms/2007b", required = true)
            protected List<HDDStatus> hddStatus;

            /**
             * Gets the value of the raidStatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRAIDStatus() {
                return raidStatus;
            }

            /**
             * Sets the value of the raidStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRAIDStatus(String value) {
                this.raidStatus = value;
            }

            /**
             * Gets the value of the hddStatus property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the hddStatus property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getHDDStatus().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link HDDStatus }
             * 
             * 
             */
            public List<HDDStatus> getHDDStatus() {
                if (hddStatus == null) {
                    hddStatus = new ArrayList<HDDStatus>();
                }
                return this.hddStatus;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="IsSpareSlot" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name",
                "isSpareSlot",
                "status"
            })
            public static class HDDStatus {

                @XmlElement(name = "Name", namespace = "http://xmlns.sony.net/d-cinema/sms/2007b", required = true)
                protected String name;
                @XmlElement(name = "IsSpareSlot", namespace = "http://xmlns.sony.net/d-cinema/sms/2007b", required = true)
                protected String isSpareSlot;
                @XmlElement(name = "Status", namespace = "http://xmlns.sony.net/d-cinema/sms/2007b", required = true)
                protected String status;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the isSpareSlot property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIsSpareSlot() {
                    return isSpareSlot;
                }

                /**
                 * Sets the value of the isSpareSlot property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIsSpareSlot(String value) {
                    this.isSpareSlot = value;
                }

                /**
                 * Gets the value of the status property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatus(String value) {
                    this.status = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "type",
        "timestamp",
        "source"
    })
    public static class MessageHeader {

        @XmlElement(name = "Id", namespace = "http://xmlns.sony.net/d-cinema/sms/2007b")
        protected byte id;
        @XmlElement(name = "Type", namespace = "http://xmlns.sony.net/d-cinema/sms/2007b", required = true)
        protected String type;
        @XmlElement(name = "Timestamp", namespace = "http://xmlns.sony.net/d-cinema/sms/2007b")
        protected long timestamp;
        @XmlElement(name = "Source", namespace = "http://xmlns.sony.net/d-cinema/sms/2007b", required = true)
        protected String source;

        /**
         * Gets the value of the id property.
         * 
         */
        public byte getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(byte value) {
            this.id = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the timestamp property.
         * 
         */
        public long getTimestamp() {
            return timestamp;
        }

        /**
         * Sets the value of the timestamp property.
         * 
         */
        public void setTimestamp(long value) {
            this.timestamp = value;
        }

        /**
         * Gets the value of the source property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSource() {
            return source;
        }

        /**
         * Sets the value of the source property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSource(String value) {
            this.source = value;
        }

    }

}
